services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  postgres:
    image: postgres:latest
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - "5433:5432"
    volumes:
        - .docker/postgresql:/var/lib/postgresql/data